Fontawesome version update
edamontology/edam-browser pull request #107
Opened 2021-04-12 21:55 UTC by raashika03

Minor change
Following [this](https://github.com/edamontology/edam-browser/commit/99428cf9a3ed5dc51844a79f50f71979e6798f9e#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051) & [this](https://github.com/edamontology/edam-browser/pull/62#discussion_r606208426) updation.
Updated the font awesome version for the propose change pages too. and then updated in the readme. So that it can be same everywhere.

2021-04-13 14:41 UTC, bryan-brancotte requested changes

2021-04-13 14:41 UTC, bryan-brancotte commented on edit.html
> +    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/5.6.0/css/font-awesome.min.css" rel="stylesheet"
more than the same version as in index.html, we should use the same cdn to reduce network usage:

https://github.com/edamontology/edam-browser/blob/main/index.html#L27

```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css">
```

2021-04-13 16:18 UTC, raashika03 commented
Thank you @bryan-brancotte I wasn't aware of this, I'm learning things :smiley: Thank you

2021-04-26 10:55 UTC, bryan-brancotte commented
learning is the goal :+1:

merging :clap:

2021-04-26 10:55 UTC, merged