Replaced the popup box to make content fully visible!
edamontology/edam-browser pull request #113
Opened 2021-04-13 06:15 UTC by secrashi

Regarding Issue #81, I replaced the popup from the right side to the left side!
Before:

![bla](https://user-images.githubusercontent.com/56053777/114504938-417c1d80-9c4d-11eb-9ba4-40d69f019030.jpg)

After:

![WhatsApp Image 2021-04-13 at 11 44 36 AM](https://user-images.githubusercontent.com/56053777/114505229-af284980-9c4d-11eb-9f14-acbf409fef8c.jpeg)

2021-04-13 14:44 UTC, bryan-brancotte requested changes
cf https://github.com/edamontology/edam-browser/issues/81#issuecomment-818697210

2021-04-13 14:44 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +            data_content = "title=\"Some associated elements\" data-toggle=\"popover\" data-placement=\"left\" data-trigger=\"hover\" data-html=\"true\" data-content=\"<table class='table table-conde
placement should be kept on the right when possible, cf https://github.com/edamontology/edam-browser/issues/81#issuecomment-818697210

2021-04-14 03:58 UTC, secrashi commented
Hey @bryan-brancotte, I have made the required changes! Please have a look.

2021-04-26 11:01 UTC, bryan-brancotte requested changes

2021-04-26 11:01 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +            data_content = "title=\"Some associated elements\" data-toggle=\"popover\" data-placement=\"auto left\" data-trigger=\"hover\" data-html=\"true\" data-content=\"<table class='table table-
Hi @secrashi :clap: you found the `data-placement=\"auto\"` ! Could you just set to `auto right`, instead of `auto left` so it cover less text on large screen. After that we are good for merging.

2021-04-26 12:44 UTC, secrashi commented on js/tree-edam-stand-alone.js
> +            data_content = "title=\"Some associated elements\" data-toggle=\"popover\" data-placement=\"auto left\" data-trigger=\"hover\" data-html=\"true\" data-content=\"<table class='table table-
Hey @bryan-brancotte, I made the required changes. Please have a look!

2021-04-26 13:13 UTC, bryan-brancotte approved these changes

2021-04-26 13:14 UTC, merged