Removed 'previously seen' title when not required!
edamontology/edam-browser pull request #119
Opened 2021-04-14 06:11 UTC by secrashi

2021-04-14 06:48 UTC, bryan-brancotte commented
Hi, your approach is good, but there is an even simpler way to do it with one css option, it recommend you to take a look at [`:last-child`](https://developer.mozilla.org/fr/docs/Web/CSS/:last-child) if you don't know it yet

2021-04-21 17:42 UTC, secrashi commented
Hey @bryan-brancotte, I have made the required changes, please have a look and let me know if anything else needs to be done!

2021-04-23 21:51 UTC, hmenager requested changes
I don't think this solution can work. Maybe use js instead?

2021-04-23 21:51 UTC, hmenager commented on css/index.css
> +.temp:last-child {
unsure if this could actually work. `:last-child` actually designates the last child element, i.e. an HTML child element, and when the list is empty the element only contains a child text node `Previously seen:`. I can't see this approach working. Maybe it'd be easier using a js-based solution?

2021-04-24 11:35 UTC, secrashi commented on css/index.css
> +.temp:last-child {
Hello @hmenager, when the list is empty the element only contains a child text node Previously seen, which is technically the last div element with class temp, so its opacity would be set to 0. When the list extends then it won't remain the last, and its opacity won't be affected. Also, this solution works on my local machine!

> I don't think this solution can work. Maybe use js instead?

I initially made the required changes using js only which can be seen in previous commits to this PR. @bryan-brancotte then suggested that using last: child property would make it easier. If you think that using js is a better option, Then I can make another pr for the same with changes in js code.

2021-04-24 21:49 UTC, hmenager commented on css/index.css
> +.temp:last-child {
You are right @secrashi . I'm sorry I actually initially didn't understand your code correctly. It works perfectly, and the solution is very elegant :clap: ! I'll merge it right away :)

2021-04-24 21:49 UTC, hmenager approved these changes

2021-04-24 21:49 UTC, merged

2021-04-25 04:54 UTC, secrashi commented on css/index.css
> +.temp:last-child {
Thank you!