Added Feature to open tree on Fullscreen.
edamontology/edam-browser pull request #141
Opened 2021-04-24 11:04 UTC by secrashi

Regarding #126!

2021-04-26 12:54 UTC, bryan-brancotte requested changes
Hi @secrashi 

It's a nice feature, and I'm eager to see it in main branch :clap: Please find attache the change requests. Do not be chocked by the number, most of them are cleanup. Two are about improving the solution to have a second icon, so not such a big deal.

2021-04-26 12:54 UTC, bryan-brancotte commented on index.html
> +
Could you revert the change made here ?

2021-04-26 12:54 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +    function toggleFullscreen( jQuery){
please re-indent

2021-04-26 12:54 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +    }
please re-indent

2021-04-26 12:54 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +document.getElementById("toggle-text").innerHTML="Open Fullscreen";
I am getting an
```
Uncaught TypeError: Cannot set property 'innerHTML' of null
    at tree-edam-stand-alone.js:672
```

2021-04-26 12:54 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +$( document ).ready( toggleFullscreen );
why triggering it on startup ?

2021-04-26 12:54 UTC, bryan-brancotte commented on index.html
> +                    <div>
More a proposition than a change request, but this code would allow to also change the icon and the text with a simple `$('exit-fullscreen').show();$('go-fullscreen').hide()` in `toggleFullscreen`. Also this alternative allows to not have "Close/Open Full Screen" at two different locations, all texts are in the button, and the js code only manage who should be rendered.
```
                        <button type="button" class="btn btn-default" id="go-fullscreen"
                        onclick="toggleFullscreen();" ><i class="fas fa-expand" aria-hidden="true"></i><span id="toggle-text" class="on-controls-hover">Open Full Screen</span>
                        </button>
                        <button type="button" class="btn btn-default" style="display:none" id="exit-fullscreen"
                        onclick="toggleFullscreen();" ><i class="fas fa-compress" aria-hidden="true"></i><span class="on-controls-hover">Exit Full Screen</span>
                        </button>
```

2021-04-26 12:54 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +        document.getElementById("toggle-text").innerHTML="Close Fullscreen";
cf comments with `$('exit-fullscreen').show();$('go-fullscreen').hide()`

2021-04-26 12:58 UTC, secrashi commented on index.html
> +
Sure, I removed the extra space!

2021-04-26 13:12 UTC, secrashi commented on js/tree-edam-stand-alone.js
> +    function toggleFullscreen( jQuery){
Sure, done!

2021-04-26 13:12 UTC, secrashi commented on js/tree-edam-stand-alone.js
> +    }
Sure, done!

2021-04-26 14:58 UTC, secrashi commented on js/tree-edam-stand-alone.js
> +$( document ).ready( toggleFullscreen );
I guess, I left it there by mistake. I used it when I was coding to check the outcome! I'll remove it.

2021-04-26 15:01 UTC, secrashi commented on index.html
> +                    <div>
That is a way easier + elegant solution, I don't know why I didn't think of it! Thank you so much for bringing this up, I'll make the changes soon!

2021-04-26 19:43 UTC, secrashi commented on js/tree-edam-stand-alone.js
> +        document.getElementById("toggle-text").innerHTML="Close Fullscreen";
Hey @bryan-brancotte, I have made all required changes, please have a look and do let me know if anything else needs to be done!

2021-04-26 19:45 UTC, secrashi commented on js/tree-edam-stand-alone.js
> +document.getElementById("toggle-text").innerHTML="Open Fullscreen";
I haven't yet figured out why you got this error since it ran perfectly fine on my local machine! Can you suggest what can be the possible reasons for this?

2021-04-26 20:13 UTC, bryan-brancotte requested changes
Well done ! Only minor reformatting changes and we are good to merge into main (I can do it if you prefer)

2021-04-26 20:13 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +        treeResize.requestFullscreen();
We can directly write ```document.getElementById("tree-and-controls").requestFullscreen();``` as treeResize is used only once

2021-04-26 20:13 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +    {
Could you mimic current formating ? example at https://github.com/edamontology/edam-browser/blob/2c1a15e3f856ff65d9f66cdbd2e127b0db3dd5be/js/tree-edam-stand-alone.js#L63 I mean the `{` right next the parenthesis

2021-04-26 20:13 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +    else
Could you mimic current formating ? example at https://github.com/edamontology/edam-browser/blob/2c1a15e3f856ff65d9f66cdbd2e127b0db3dd5be/js/tree-edam-stand-alone.js#L66

2021-04-27 03:00 UTC, secrashi commented on js/tree-edam-stand-alone.js
> +        treeResize.requestFullscreen();
yaa sure, done!

2021-04-27 03:01 UTC, secrashi commented on js/tree-edam-stand-alone.js
> +    else
Done! I have made the changes, please have a look!

2021-04-27 03:06 UTC, secrashi commented on js/tree-edam-stand-alone.js
> +document.getElementById("toggle-text").innerHTML="Open Fullscreen";
Thanks, @raashika03, but it still didn't explain the fact why the error showed up on his screen while not on mine.

2021-04-27 14:49 UTC, bryan-brancotte approved these changes
:clap:

2021-04-27 14:51 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +document.getElementById("toggle-text").innerHTML="Open Fullscreen";
I think it could be an async issue, or browser dependent issue

2021-04-27 14:52 UTC, merged