Removed toUpperCase function!
edamontology/edam-browser pull request #142
Opened 2021-04-24 13:27 UTC by secrashi

I kept getting an error that '_toUpperCase is not a function_' whenever I tried to load deprecated terms from the drop-down menu. 

![WhatsApp Image 2021-04-24 at 6 34 54 PM](https://user-images.githubusercontent.com/56053777/115960005-b17f8300-a52c-11eb-8d95-4c7906b7bf03.jpeg)

- I tried to look for possible solutions, and I got another error saying '_cannot read property 'toUpperCase of undefined_' , I realized that while loading deprecated terms, the value of a and b would possibly be an empty string. I tried to use the if-else situation, where it is not an empty string then `a=textAccessor(a).toUpperCase();`. But this too didn't work and I haven't yet figured out why. 
- Another possible solution that seemed to me was to remove toUpperCase function, though I wasn't sure, if it would affect other elements of the website. After implementing this, I checked if any other element was affected due to this, but I can't find any. 
Can @hmenager @bryan-brancotte @matuskalas let me know if this is the correct solution to the problem? If not, then can u give me a hint on which direction to look for?

2021-04-26 13:49 UTC, bryan-brancotte commented
Hi @secrashi 

Thanks for spotting the issue, could you indicated what was your search of terms ?

The toUpperCase is need in order to sort while not beeing sensible to the case, without it names would be sorted like:
```
Alice
Charlie
Daniel
bob
eva
```

So here we have to option : 
 *  make sure `textAccessor(a)` returns something
 * use a default blank string when `textAccessor(a)` returns nothing

I would prefer to change the `textAccessor` implementation that sometime returns undefined values as it could also cause issue elsewhere later.

2021-04-26 14:44 UTC, secrashi commented
Hello @bryan-brancotte, 
> Thanks for spotting the issue, could you indicated what was your search of terms ?
- I received this error `Uncaught TypeError: textAccessor(...).toUpperCase is not a function` when I tried to click the option '_Deprecated Terms_' and '_All branches and deprecated terms_' from the dropdown menu.


> So here we have to option :
> 
> * make sure `textAccessor(a)` returns something
> * use a default blank string when `textAccessor(a)` returns nothing
> 
> I would prefer to change the `textAccessor` implementation that sometime returns undefined values as it could also cause issue elsewhere later.

Sure, I'll look for ways to do this! Should I make a different PR for the changes or commit the changes here directly?

2021-04-26 20:03 UTC, bryan-brancotte commented
> * I received this error `Uncaught TypeError: textAccessor(...).toUpperCase is not a function` when I tried to click the option '_Deprecated Terms_' and '_All branches and deprecated terms_' from the dropdown menu.

Thanks for the intel

2021-04-27 14:43 UTC, bryan-brancotte requested changes
Hi,
I don't think that `parseInt` is the solution. Before solving the issue, you should identify which node/element cause the problem. I let you search for it, ping me if you want some help

2021-04-27 14:43 UTC, bryan-brancotte commented on js/tree-reusable-d3.js
> +                        if (parseInt(a) > parseInt(b))
I am not sure that is solves the issue as parseInt("ee") returns NaN.

2021-05-26 10:58 UTC, bryan-brancotte commented
work is being carried on in #181

2021-05-26 10:58 UTC, closed without merging