Added logo and icons in the header
edamontology/edam-browser pull request #143
Opened 2021-04-26 17:54 UTC by raashika03

### Checklist

- [x] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] I only changed lines related to my PR (no bulk reformating)
- [x] I indicated the source and check the license if I re-use code, or I did not re-use code
- [x] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

### Issue

close/fix/resolve #75 

### Details

Before:
![Screenshot from 2021-04-26 23-19-46](https://user-images.githubusercontent.com/45493793/116127925-ff8bb680-a6e5-11eb-929e-2062dc8647a9.png)
After:
![Screenshot from 2021-04-26 23-17-58](https://user-images.githubusercontent.com/45493793/116127778-d8cd8000-a6e5-11eb-8fe6-beaeb23796df.png)
![Screenshot from 2021-04-26 23-18-08](https://user-images.githubusercontent.com/45493793/116127770-d703bc80-a6e5-11eb-9d5b-16e1b5a9b1e1.png)

@bryan-brancotte This's the initial version Please suggest changes for like what should I write beside github/gitter icon instead of edam-browser.

2021-04-26 18:07 UTC, raashika03 commented
I'll add more commits when you'll clarify your thoughts as I asked [here](https://github.com/edamontology/edam-browser/issues/75#issuecomment-826885204). For now, this is the initial version.

2021-04-26 20:01 UTC, bryan-brancotte commented
Hi @raashika03 

I like the look, although I think we could save space by moving the button like this:
![116127778-d8cd8000-a6e5-11eb-8fe6-beaeb23796df](https://user-images.githubusercontent.com/11556772/116141688-4b842e80-a6d9-11eb-836b-3ac250644e1d.png)


My main concerne is regarding its implementation, I read the css and html and you kept the `col-xs-12 ...` will  adding `id="..."` along with `position:absolute`. Mixing both of them is not a good practice, `col-xs-12` and alike are meant to be relative, so fixing it or its descendant to absolute can only end up with complicated css code and unexepected behavior.

Although I think good results could be achieve with position absolute, I recommend you to try using `dispay:flex` (here are some [docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox)). It will allow you to cut the space, automatically assign the blank space to one or another.

Here is an example of how the area should be cut, when using display:flex
![cut](https://user-images.githubusercontent.com/11556772/116142663-78851100-a6da-11eb-861c-5b45f675d9f7.png)
Refinement could done also to keep the button and the search bar in the vertical middle of the global header area.

2021-04-26 20:04 UTC, raashika03 commented
Oki @bryan-brancotte I understood well thank you! I'll implement it this way.

2021-04-26 21:33 UTC, raashika03 commented
@bryan-brancotte done! check once please!

2021-04-27 12:22 UTC, raashika03 commented
@bryan-brancotte it's done! Please summarize your views.
![Screenshot from 2021-04-27 03-03-35](https://user-images.githubusercontent.com/45493793/116153639-46d56f80-a705-11eb-9dba-793150ae7167.png)

2021-04-27 13:37 UTC, bryan-brancotte requested changes
Hi, Here are some minor changes but you can go more in the usage of display flex. I'll soon do a PR on your branch so you can see the difference, adapte/accept.

2021-04-27 13:37 UTC, bryan-brancotte commented on index.html
>          </div>
should also have been removed

2021-04-27 13:37 UTC, bryan-brancotte commented on index.html
> +                <p>
using `<p>` with `display: inline-block;` is the same as using span, so why no using it ? (and adding the margin in the css?)

2021-04-27 13:41 UTC, raashika03 commented
Actually I think these div opening and closing are handled I moved that EDAM/ custom inside that flex-container class so only change in opening tag is showing. 
I checked its working after final commit. 
It's working sound. Correct me if i'm wrong.

2021-04-27 14:01 UTC, bryan-brancotte commented on index.html
> +            <div>
@raashika03 as this div is not closed for now it cause the second (buttons) and third (search bar) block to be in the first (logo&title). Check the PR I made to your branche, you can git clone to see how it works, do not forget to refresh cache

2021-04-27 14:29 UTC, raashika03 commented
![Screenshot from 2021-04-27 19-55-11](https://user-images.githubusercontent.com/45493793/116258735-d37a3f00-a792-11eb-9fd1-6e310bfcb765.png)
So this's final look @bryan-brancotte 
And I apologise for those indentation, will keep in mind from next time :sweat_smile:

2021-04-27 14:33 UTC, raashika03 commented
But now header kind of design is removed. I kept that knowingly and aligned space bar and that like this to prevent capturing more space.
But, this also looks good. though spacing seems more.

2021-04-27 15:03 UTC, bryan-brancotte commented
The screenshot is not what I get (even before my two quick commit), maybe refreshing the css (ctrl shift F5) ?

2021-04-27 15:03 UTC, raashika03 commented
There's no cache issue I checked.

2021-04-27 15:04 UTC, raashika03 commented
I think I made some mistake while reverting changes.

2021-04-27 16:31 UTC, raashika03 commented
![Screenshot from 2021-04-27 21-58-57](https://user-images.githubusercontent.com/45493793/116278198-e8130300-a7a3-11eb-9c58-5cfb3ac9ed53.png)
This's the final result. I messed up locally (checked by deleting the previous repo locally and changing the code in this PR in that local new repo). Code is sound to be merged. @bryan-brancotte

2021-04-28 07:43 UTC, raashika03 commented
Twitter logo is there at the bottom. @bryan-brancotte

2021-04-28 07:44 UTC, bryan-brancotte approved these changes
We are good to merge

2021-04-28 07:45 UTC, bryan-brancotte commented
> Twitter logo is there at the bottom. @bryan-brancotte

Yes, but I had the feeling that we were adding what was formerly at the bottom at the top, I was about to create an issue on whether we should now delete them from the bottom as they are in the header

2021-04-28 07:46 UTC, raashika03 commented
No but at the the bottom all of them points to edamontology not to Edam browser.

2021-04-28 07:49 UTC, raashika03 commented
Can you check [this] once. 
A proposal regarding the footer has been covered up. 
So removal might not be needed.

2021-04-28 07:58 UTC, bryan-brancotte commented
I missed #77, ok so no need for a new issue as the question is already raised there.

I though the gitter was also edam-browser in the bottom. As edam-browser does not have a twitter account, pointing to edamontology twitter is not so invalide.

I thus propose we keep the twitter top and bottom, leave the footer as is a, and let #77 take care of it.

P.S: once https://github.com/edamontology/edamontology/pull/674 is merge, logo will magically re-appear.

2021-04-28 07:59 UTC, bryan-brancotte commented
so ? merging ?

2021-04-28 08:01 UTC, raashika03 commented
Yes we're good to merge.

2021-04-28 08:02 UTC, merged