add a development run option that works on all platforms and IDEs
edamontology/edam-browser pull request #151
Opened 2021-04-28 13:06 UTC by sunny775

This PR proposes a better alternative to run the EDAM browser locally, as requested by @bryan-brancotte 
[Live Server](https://www.npmjs.com/package/live-server) is a minibal, lightweight nodejs development server with live reload capability.  It requires that developer have nodejs and npm installed in their environment.
I believe it will be the best option for running the project locally as it is better than previous options in the following ways:
- [x] It works on all platforms and IDEs, without any extra config
- [x] Unlike the previous options, it has live reload capability. The sever refreshes the browser every time the developer makes a change to the code 
- [x] Literally every developer has nodejs and npm in their environment, which are the only dependencies of Live Server

### Checklist

- [x] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] I only changed lines related to my PR (no bulk reformating)
- [x] I indicated the source and check the license if I re-use code, or I did not re-use code
- [x] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

### Closes #121

2021-04-28 14:20 UTC, bryan-brancotte requested changes
Despite my small request changes, good job thanks ! It would have helped many of us when starting on this project to have this at the time.

2021-04-28 14:20 UTC, bryan-brancotte commented on README.md
> +2. Install Live Server "globally": `npm install -g live-server`
maybe not a global installation ? as sometime dev do not have root access.

2021-04-28 14:20 UTC, bryan-brancotte commented on README.md
> -##### Option 2:
Keep it as a fallback if dev doesn't have nodejs and npm ? I'm thinking to ontology developer that will run the app locally to browse their dev version of the ontology

2021-04-28 14:20 UTC, bryan-brancotte commented on package.json
> +    "dev": "live-server",
works like a charm :clap: thanks

2021-04-28 14:58 UTC, sunny775 commented on README.md
> -##### Option 2:
Yes, the vscode extension option is a fallback for those who don't have nodejs and npm

2021-04-28 14:58 UTC, sunny775 commented on README.md
> +2. Install Live Server "globally": `npm install -g live-server`
Per project installation will mean adding to the project, a js file ( say server.js ) with the following content:
![server_js](https://user-images.githubusercontent.com/49409497/116423372-881a6c00-a838-11eb-989b-f322c7f2c15c.png)
Then, the `dev script` will then be something like `"dev": "node server.js"`
If you wouldn't mind this extra file and would like it to be added as a `devDependency` , I can make the necessary changes and push the code

2021-04-28 15:00 UTC, sunny775 commented on package.json
> +    "dev": "live-server",
Thanks @bryan-brancotte

2021-04-28 15:07 UTC, sunny775 commented on README.md
> +2. Install Live Server "globally": `npm install -g live-server`
Though I think every dev has a way to get around root access, like adding user to `sudoers` in linux or running the   powershell as administrator for windows

2021-04-28 15:43 UTC, bryan-brancotte commented on README.md
> +2. Install Live Server "globally": `npm install -g live-server`
I just ran `npm install live-server` at the time (thus without server.js) and it worked like a charm. Also it really can happen that dev doesn't have root power, and cannot have it.

2021-04-28 15:45 UTC, bryan-brancotte commented on README.md
> -##### Option 2:
My comment was not on the good line, I was talking of the python option, I know some dev ou almost do everything in cli and vim, so indeed keeping python3 option is needed.

2021-04-28 17:04 UTC, sunny775 commented on README.md
> -##### Option 2:
Ok. I've added it

2021-04-28 17:13 UTC, sunny775 commented on README.md
> +2. Install Live Server "globally": `npm install -g live-server`
You're right! Wow! I just ried it and it works perfeclty. I guess it works because we're not running `live-server`  directly, but through `npm` which would normally search through the dependency tree before yelling *command not found*

I've added it as a `devDependency` , and also included the auto-generated `package-lock.json`  file

2021-04-29 14:53 UTC, bryan-brancotte approved these changes
Thanks :+1:

2021-04-29 14:53 UTC, bryan-brancotte commented on package.json
> +    "live-server": "^1.2.1"
I would have added `"live-server": "^1.2.1"` before `jshint` just to prevent editing the line of jshint with the addition of a comma, it allows to keep a clear git history. As it is now someone can believe that you changed jshint version while it is not the case.

2021-04-29 14:53 UTC, bryan-brancotte commented on README.md
> -##### Option 2:
Thanks :+1:

2021-04-30 02:25 UTC, sunny775 commented on package.json
> +    "live-server": "^1.2.1"
@bryan-brancotte I've done that

2021-04-30 10:16 UTC, bryan-brancotte approved these changes
great thanks !

2021-04-30 10:16 UTC, merged