fixed edit page alignment on using search box
edamontology/edam-browser pull request #169
Opened 2021-05-03 22:56 UTC by raashika03

### Checklist

- [X] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [X] I only changed lines related to my PR (no bulk reformatting)
- [X] I indicated the source and check the license if I re-use code, or I did not re-use code
- [X] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

### Issue

close #103

### Details
Can be seen live [here](https://raashika03.github.io/edam-browser/edit.html?parent=http://edamontology.org/data_0006&branch=edam)

2021-05-03 23:14 UTC, raashika03 commented
![IMG_20210504_044310](https://user-images.githubusercontent.com/45493793/116944528-4d2e9300-ac93-11eb-8f7d-b5c66ac10eb2.jpg)
And if this kind of version is needed then desktop version is available on Android on which this problem generates.

2021-05-04 09:05 UTC, bryan-brancotte requested changes

2021-05-04 09:05 UTC, bryan-brancotte commented on edit.html
> +    <meta name="viewport" content="width=device-width, user-scalable=no">
Well found :clap:. After reading some post on the matter, I found that scaling for people with "visual imparment" i.e have at least glasses. I propose that you use instead
```<meta name="viewport" content="width=device-width, initial-scale=1.0">```

From what I have tested it works fine, and keep the zoom ability.

2021-05-04 09:12 UTC, raashika03 commented on edit.html
> +    <meta name="viewport" content="width=device-width, user-scalable=no">
Done @bryan-brancotte :) I hardly see any difference :sweat_smile:

2021-05-04 09:21 UTC, raashika03 commented on edit.html
> +    <meta name="viewport" content="width=device-width, user-scalable=no">
Ok may be people with spects can spot any difference :sweat_smile:

2021-05-04 09:21 UTC, bryan-brancotte commented
The support is not that good https://caniuse.com/mdn-http_headers_viewport-width but it is still a good option. I propose merge, and if one day someone find better we'll switch to it.

2021-05-04 09:21 UTC, bryan-brancotte approved these changes

2021-05-04 09:22 UTC, merged

2021-05-04 09:24 UTC, bryan-brancotte commented
P.S: I also applied it to main page

2021-05-04 09:28 UTC, raashika03 commented
> P.S: I also applied it to main page

ok then I'll move that search icon to left side cause that's overlapping.

I tried solving #102 like this but I liked the desktop version more for mobile screen size for the main page, so was looking for some other approah if possible.