#50 Showing relevant terms in term creation form
edamontology/edam-browser pull request #174
Opened 2021-05-04 14:56 UTC by pooja2299

### Checklist

- [x] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] I only changed lines related to my PR (no bulk reformatting)
- [x] I indicated the source and check the license if I re-use code, or I did not re-use code
- [x] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

### Issue

resolve #50

2021-05-04 14:58 UTC, pooja2299 commented
@bryan-brancotte .Plse review this

2021-05-05 07:27 UTC, bryan-brancotte requested changes
Hi @pooja2299 

Now there is bluk reformating I can see you work and review it :)

I like your approach :+1: , please find attached request changes. They keep your approach will working on a more generic solution.

2021-05-05 07:27 UTC, bryan-brancotte commented on edit.html
> +                <div class="row operation_rel data_rel">
add `optional_rel` css class to every block that may be hidden, such as this one

2021-05-05 07:27 UTC, bryan-brancotte commented on edit.html
> +                <div class="row format_rel">
add `optional_rel` css class

2021-05-05 07:27 UTC, bryan-brancotte commented on edit.html
> +                <div class="row operation_rel">
add `optional_rel` css class

2021-05-05 07:27 UTC, bryan-brancotte commented on edit.html
> +                <div class="row operation_rel">
add `optional_rel` css class

2021-05-05 07:27 UTC, bryan-brancotte commented on js/edit.js
> +    if (s_branch === "operation") {
instead of show/hide every block for evey branch, you could do something more generic:

First you hide all optional block with `$('.optional_rel').hide();` 

Then show only appropriate branch in **one** line. I let you find how, ping me if you want the solution.

2021-05-05 07:27 UTC, bryan-brancotte commented on js/edit.js
> +    var s_branch = getUrlParameter('term') + getUrlParameter('parent');
this work perfectly fine, but when reading too fast one can wonder why concatenate this two string. To avoid misunderstanding I suggest that you use  `||` and thus clearly state that both are not set at the same time.
```var s_branch = getUrlParameter('term') || getUrlParameter('parent'); ```

2021-05-05 13:19 UTC, pooja2299 commented
> Hi @pooja2299
> 
> Now there is bluk reformating I can see you work and review it :)
> 


I didnt understand this line . Bulk reformatting is still there ?

2021-05-05 13:19 UTC, pooja2299 commented on js/edit.js
> +    var s_branch = getUrlParameter('term') + getUrlParameter('parent');
ok i will change it

2021-05-05 13:20 UTC, pooja2299 commented on js/edit.js
> +    if (s_branch === "operation") {
> instead of show/hide every block for evey branch, you could do something more generic:
> 
> First you hide all optional block with `$('.optional_rel').hide();`
> 
> Then show only appropriate branch in **one** line. I let you find how, ping me if you want the solution.

yes, i would like to know this aooroach. I pinged you on gitter.

2021-05-05 15:24 UTC, pooja2299 commented
@bryan-brancotte please review it . After this i am thinking to add `Is Identifier Of` term also in the form.

2021-05-06 07:08 UTC, bryan-brancotte requested changes

2021-05-06 07:08 UTC, bryan-brancotte commented on js/edit.js
> +    if (s_branch === "operation") {
So, when `s_branch === "operation"` you want to `$('.operation_rel').show();`, when `s_branch === "data"` you want to `$('.data_rel').show();`, and so on.

So in one line you just want to 
```
$('.' + s_branch + '_rel').show();
```

2021-05-06 09:08 UTC, pooja2299 commented
Thanks a lot for this suggestion. It is indeed a short and precise solution.:raised_hands:

2021-05-06 10:17 UTC, bryan-brancotte commented
> > Hi @pooja2299
> > Now there is bluk reformating I can see you work and review it :)
> 
> I didnt understand this line . Bulk reformatting is still there ?

sorry, the correct sentence was 
> Now there is **no** bluk reformating I can see you work and review it :)

2021-05-06 10:19 UTC, bryan-brancotte commented
> @bryan-brancotte please review it . After this i am thinking to add `Is Identifier Of` term also in the form as mentioned in the issue #50 .

Do you want to do it in this PR, or I create an issue and you/someone will tack the issue with a new PR

2021-05-06 12:29 UTC, pooja2299 commented
Identifier is a child of data branch. To add Is_identifier_of term should i add identifier in typeDict(line 3 in edit.js) dictionary?

> > @bryan-brancotte please review it . After this i am thinking to add `Is Identifier Of` term also in the form as mentioned in the issue #50 .
> 
> Do you want to do it in this PR, or I create an issue and you/someone will tack the issue with a new PR ?

I think we can create a new issue and then I can make a PR regarding it.

2021-05-06 14:28 UTC, merged