Alerts user when loading custom ontology fails!
edamontology/edam-browser pull request #180
Opened 2021-05-07 06:33 UTC by secrashi

### Checklist

- [x] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] I only changed lines related to my PR (no bulk reformatting)
- [x] I indicated the source and check the license if I re-use code, or I did not re-use code
- [x] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

### Issue

fix #137

2021-05-07 06:39 UTC, secrashi commented on js/tree-edam-stand-alone.js
> -        $("#edamAccordion>.panel-group").remove();
I removed this code so that when custom ontology fails to load, the details section wouldn't be removed. But It will also keep it as previously seen terms when a custom ontology is loaded. I thought it is better to keep them as previously seen terms, then costing on our User experience, <as of now>.

2021-05-10 11:29 UTC, bryan-brancotte requested changes
Hi

Sorry for the long reviews. Please create a PR/new branch with only the changes in tree-reusable-d3.js so git history is intact.

2021-05-11 06:31 UTC, secrashi commented on js/tree-edam-stand-alone.js
> -        $("#edamAccordion>.panel-group").remove();
Hi @bryan-brancotte, Yes I understand that previous ontology is not relevant while loading custom ontology, but the real question is are we ready to compromise our UI and UX for this? 
Please let me know if you don't think in similar way, I just thought that until we find a permanent (and better) solution to this, we can alter this to keep our UX the same.

2021-05-11 08:27 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> -        $("#edamAccordion>.panel-group").remove();
Hi @secrashi, keeping the old detail panel when failing at loading a new ontology is an UX issue : we were working with ontology A, we tried B, we thus must have information regarding B, or why it has failed to be loaded. You patch is to inform the user about failure of B, but removing this line also show information for A which is confusing. So in order to not compromoise the UX experience, we must not remove this line.

2021-05-11 08:43 UTC, secrashi commented on js/tree-edam-stand-alone.js
> -            if(typeof json.meta=="undefined"){
> Could you explain when this scenario occurs (json being null) ? 

Yes, Json would be null when we upload non-json files in the input field. 
>a simpler test on json == null and then returning would do the same and change less lines (thus keeping git history easily accessible)

Yes, I agree. I'll make this change asap. Also, I'm sorry for not taking git history into consideration. I'm not habitual of it but I'm learning. Thanks!

2021-05-18 15:10 UTC, merged