Quick fix to align footer icons at centre!
edamontology/edam-browser pull request #185
Opened 2021-05-11 09:43 UTC by secrashi

### Checklist

- [x] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] I only changed lines related to my PR (no bulk reformatting)
- [x] I indicated the source and check the license if I re-use code, or I did not re-use code
- [x] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

### Details

![WhatsApp Image 2021-05-11 at 3 10 50 PM](https://user-images.githubusercontent.com/56053777/117794855-4099d400-b26b-11eb-9e35-25056096b349.jpeg)
The footer icons look more aligned towards the right side. I just used `transform` property of CSS to align them at centre.

2021-05-12 23:28 UTC, raashika03 requested changes

2021-05-12 23:28 UTC, raashika03 commented on css/index.css
> +    transform: translate(-50%, -50%);
Hi, I think it's better to approach it like this.
.communicate {
	text-align: center;
    color: #33CAFF;
}

code reduction and easy to understand. 

Both works the same.

2021-05-12 23:45 UTC, raashika03 requested changes

2021-05-12 23:45 UTC, raashika03 commented on css/index.css
> +    transform: translate(-50%, -50%);
Hi, I think it's better to approach it like this.
.communicate {
	text-align: center;
    color: #33CAFF;
}


Replace 
`position: absolute;`
  `  left: 50%;`
   ` transform: translate(-50%, -50%);`

with
`text-align: center;`

code reduction and easy to understand. 

Both works the same.

Moreover, it'll be easier later on, to style for #77 if needed.

2021-05-13 03:03 UTC, secrashi commented on css/index.css
> +    transform: translate(-50%, -50%);
Agreed. Thanks :)

2021-05-18 13:03 UTC, closed without merging