Updated links to other browsers
edamontology/edam-browser pull request #230
Opened 2021-08-04 20:55 UTC by matuskalas

- Commented out AberOWL, as it's outdated and contains some weirdness in concept attributes
- Changed WebProtégé link to the "dev" version
- Added notes on what versions are displayed

### Checklist

- [x] I indicated which issue (if any) is closed with this PR using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] I only changed lines related to my PR (no bulk reformatting)
- [x] I indicated the source and check the license if I re-use code, or I did not re-use code
- [x] I made my best to solve only one issue in this PR, or explain why multi had to be solved at once.

2021-08-05 09:14 UTC, bryan-brancotte requested changes
I'll push proposed changes

2021-08-05 09:14 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +            "<a target=\"_blank\" href=\"https://webprotege.stanford.edu/#projects/4befad5f-f27b-430c-a07d-fcf635093169/edit/Classes?selection=Class(%3Chttp://edamontology.org/"+identifier+"%3E)\">We
What is the difference between `(dev)` here and `(latest stable)` ?

2021-08-05 09:14 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +            "<a target=\"_blank\" href=\"http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid="+uri+"\">BioPortal</a> (newest \"unstable\")"+
`(newest \"unstable\")` `(latest stable)` takes a lot of space, maybe using title ?

2021-08-05 22:31 UTC, matuskalas commented on js/tree-edam-stand-alone.js
> +            "<a target=\"_blank\" href=\"https://webprotege.stanford.edu/#projects/4befad5f-f27b-430c-a07d-fcf635093169/edit/Classes?selection=Class(%3Chttp://edamontology.org/"+identifier+"%3E)\">We
"dev" is the version under development, possibly newer than "unstable".

2021-08-05 22:34 UTC, matuskalas commented on js/tree-edam-stand-alone.js
> +            "<a target=\"_blank\" href=\"http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid="+uri+"\">BioPortal</a> (newest \"unstable\")"+
Yes, that might be a problem. Million thanks for your commits! 👍🏽 I'll test & experiment a bit around. But won't manage right now before your vacation 😉

2021-08-06 09:18 UTC, bryan-brancotte commented
![Peek 06-08-2021 11-17](https://user-images.githubusercontent.com/11556772/128488085-b6a59288-49c7-41ed-b042-12ff74ff5ece.gif)

A graphical bug remains on the link on the right, but works otherwise. Ready to merge

2025-05-09 11:30 UTC, merged