Communication logos added
edamontology/edam-browser pull request #62
Opened 2021-03-31 00:04 UTC by raashika03

![Screenshot from 2021-03-31 05-19-52](https://user-images.githubusercontent.com/45493793/113071506-7c5c6b00-91e2-11eb-8441-5ad51e08a0a4.png)
Added the available means of communication between the developer community, user and the project maintainer.

2021-03-31 01:55 UTC, matuskalas commented
A great idea, also #61, big thanks for those! 🙌🏽

There are a couple of things to consider in a broader context:
 - Link to GitHub and Gitter: Should they be for the [ontology](https://github.com/edamontology/edamontology) or for the [browser](https://github.com/edamontology/edam-browser) (perhaps the latter is better covered by the ideas in #61?)
 - This ontology browser can be used also by other ontologies than EDAM itself, so ideally these links would be configurable, or even cooler somehow read from the loaded ontology file (we could add them to the "source" OWL file in some "standardised" form)

What are your thoughts @hmenager @bryan-brancotte? (not urgent)

2021-03-31 02:22 UTC, raashika03 commented
> * Link to GitHub and Gitter: Should they be for the [ontology](https://github.com/edamontology/edamontology) or for the [browser](https://github.com/edamontology/edam-browser) (perhaps the latter is better covered by the ideas in #61?)

Adding ontology is also ok if question related to browser is answered in the ontology channel also (for now maintainers are same for both). I just wanted to specify so that if in future maintainers handling both the repoository ain't same then the user or the newbie contributor don't have to face problems while figuring out the solution to their doubts. 
> * This ontology browser can be used also by other ontologies than EDAM itself, so ideally these links would be configurable, or even cooler somehow read from the loaded ontology file (we could add them to the "source" OWL file in some "standardised" form)

How can we make the links to the destination configurable. I mean what condition do you want to use depending on which the address of the destination will change itself. I don't know if I understood the things properly as you mentioned. Are you planning to change some files in [edamontology](https://github.com/edamontology/edamontology) repo? 

> What are your thoughts @hmenager @bryan-brancotte? (not urgent)

2021-04-01 15:32 UTC, raashika03 commented
Adding for clarity 
Desktop version look, position of the logos wrt other elements.
![Screenshot from 2021-04-01 20-57-19](https://user-images.githubusercontent.com/45493793/113317640-319b3a00-932d-11eb-8f8f-aae1b4d65648.png)

2021-04-01 22:49 UTC, matuskalas commented
Thank you so much again for these suggestions, I find them extremely useful! 👍🏽
Something we didn't think much about before 🤔

We discussed this with @hmenager today, and I will later document the conclusions we ended up with. It'd be awesome if you then continue working on this @raashika03 after you're done with your other issues.
There will also be some extra work on the https://github.com/edamontology/edamontology and UX+design sides complementing this (best done beforehand), which someone else might be able to help with, while you're busy with other issues 😉

2021-04-02 04:06 UTC, raashika03 commented
Just found out that there's an email address too. this can also be added. 
[edam ontology](edam@elixir-dk.org) 

adding cause I might forget later on :(

If there're more means of communication available then don't forget to add them in the conclusion which you'll document @matuskalas

2021-04-02 12:12 UTC, hmenager requested changes

2021-04-02 12:12 UTC, hmenager commented on index.html
> +     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
@raashika03 I see there are two imports of font-awesome on lines 27-28, first being version 4.7.0, second being version 5.0.8. Since it looks like you added 5.0.8, I guess this is because this version includes icon which were not available in v4.7.0. Do you think we could remove v4.7.0 then?

2021-04-02 12:12 UTC, hmenager commented on index.html
> +<div class="footer-tools"> <a title="Improve this document, receive free virtual hugs ♥" href="https://github.com/edamontology/edam-browser/blob/main/CONTRIBUTING.md">Edit this Page</a> &nbsp;<a clas
this line is already part of PR #61 . Since I will be merging #61 first, you might have to manage a conflict there before you are able to merge. Do not hesitate to ask for help if needed for that step!

2021-04-02 13:05 UTC, raashika03 commented on index.html
> +     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
yes we can remove that, I checked just now there's no effect of its removal.
Earlier I didn't remove cause I thought bootstrap and font awesome have different styling. But now it's clear. Thank you for pointing out the same. :)

2021-04-02 13:18 UTC, raashika03 commented on index.html
> +<div class="footer-tools"> <a title="Improve this document, receive free virtual hugs ♥" href="https://github.com/edamontology/edam-browser/blob/main/CONTRIBUTING.md">Edit this Page</a> &nbsp;<a clas
I updated so that line can be same in both the PR, I think there won't be conflict now.
Still if it persists then I'll do as you directed other outreachy contributor to resolve conflict.

2021-04-03 09:04 UTC, hmenager commented
Thanks a lot for this last improvement @raashika03. Now, to answer specific comments from @matuskalas : 
>     * Link to GitHub and Gitter: Should they be for the [ontology](https://github.com/edamontology/edamontology) or for the [browser](https://github.com/edamontology/edam-browser) (perhaps the latter is better covered by the ideas in #61?)
> 
>     * This ontology browser can be used also by other ontologies than EDAM itself, so ideally these links would be configurable, or even cooler somehow read from the loaded ontology file (we could add them to the "source" OWL file in some "standardised" form)
> 
> 
> What are your thoughts @hmenager @bryan-brancotte? (not urgent)

My thoughts on this:
- Links to GitHub and Gitter should be to `edamontology` channels, i.e. https://github.com/edamontology/edamontology and https://gitter.im/edamontology/edamontology.
- They should indeed be configurable, but I would advocate that we do not request this as part of this PR. This way we can merge this more quickly, and this about how best to make it configurable in a simple and integrated way with @edamontology.

2021-04-03 10:30 UTC, matuskalas commented
I agree with @hmenager, that it'll be good to merge the current version now 👍🏽

And creating separate issues for:
- making this configurable in https://github.com/edamontology/edamontology/blob/main/EDAM_dev.owl
- extending with more links/info (_e.g._ license, ...)
- putting it into some kind of _About_ menu|"splashscreen"

Removing "draft" and "WIP", should we proceed towards merge now?

2021-04-03 10:36 UTC, matuskalas commented
Too fast, sorry, we still want to have those links pointing to https://github.com/edamontology/edamontology and https://gitter.im/edamontology/edamontology 😊

2021-04-03 10:40 UTC, matuskalas commented on index.html
> +
https://github.com/edamontology/edamontology
(I agree that we also want links to the _edam-browser_ repo itself, but somewhere else in the interface, perhaps hidden in some _About_ menu|"splashscree")

2021-04-03 10:41 UTC, matuskalas commented on index.html
> +
Same here with https://gitter.im/edamontology/edamontology
(and links to the _edam-browser_ chan elsewhere)

2021-04-03 10:42 UTC, matuskalas commented on index.html
> +	<a rel="noopener noreferrer nofollow" target="_blank" href="https://twitter.com/edamontology" title="Follow EDAM ontology on Twitter" class="fab fa-twitter fa-2x"></a>
maybe enough with "Follow on Twitter"

2021-04-03 12:29 UTC, raashika03 commented
Done with all the requested changes and resolved the conflict, now ok for merging.
@matuskalas @hmenager

2021-04-03 12:31 UTC, raashika03 reviewed
Removed conflict, I was exploring this review option :P HAHA

2021-04-03 12:46 UTC, raashika03 commented on index.html
> +	<a rel="noopener noreferrer nofollow" target="_blank" href="https://twitter.com/edamontology" title="Follow EDAM ontology on Twitter" class="fab fa-twitter fa-2x"></a>
Done! @matuskalas

2021-04-03 17:01 UTC, hmenager approved these changes

2021-04-03 17:01 UTC, hmenager commented on index.html
> +
done

2021-04-03 17:02 UTC, merged

2021-04-03 17:57 UTC, raashika03 commented
![Screenshot_2021-04-03-23-18-08-39](https://user-images.githubusercontent.com/45493793/113487120-cd66aa80-94d3-11eb-8c0c-c1946a8ad03f.png)
![IMG20210403231847](https://user-images.githubusercontent.com/45493793/113487129-d8b9d600-94d3-11eb-9860-6b297d41b6ce.jpg)
@hmenager @matuskalas how I can check locally how it looks on phone size, I checked for laptop minimising the size,  but it seems that didn't work

2021-04-03 17:59 UTC, raashika03 commented
Do you think changing the code from position absolute to relative will work in this case.
`.footer-tools {
    position: relative; //position: relative?
    right: 2rem;
    height: 0;
    text-align: right;
}`

2021-04-04 17:55 UTC, pooja2299 commented
> @hmenager @matuskalas how I can check locally how it looks on phone size, I checked for laptop minimising the size, but it seems that didn't work

@raashika03  you can view it in your chrome browser itself. Open the local page and open the inspect window (ctrl + shift + i).
Then click on the toggle device toolbar at the top.
![image](https://user-images.githubusercontent.com/44069818/113517327-dcfdf600-959c-11eb-9ad7-a7a4931f434f.png)
 Hope this little hack helps you.

2021-04-04 18:57 UTC, raashika03 commented
> > @hmenager @matuskalas how I can check locally how it looks on phone size, I checked for laptop minimising the size, but it seems that didn't work
> 
> @raashika03 you can view it in your chrome browser itself. Open the local page and open the inspect window (ctrl + shift + i).
> Then click on the toggle device toolbar at the top.
> ![image](https://user-images.githubusercontent.com/44069818/113517327-dcfdf600-959c-11eb-9ad7-a7a4931f434f.png)
> Hope this little hack helps you.

Thank you so much @pooja2299 I was not aware of this option :face_with_head_bandage: