#52 More explicit placeholder text for search box
edamontology/edam-browser pull request #66
Opened 2021-03-31 18:26 UTC by pooja2299

Added my solution to issue #52.

2021-04-01 07:41 UTC, bryan-brancotte commented
Hi @pooja2299 

Thanks for the PR, indeed the text you propose is better than what was initially there :medal_sports: . Note that adding an icon would also have been a good idea.

I can only recommend that now you grab another "good first issue".

Best wishes

2021-04-01 09:00 UTC, hmenager requested changes
Thank you so much @pooja2299! I just asked for two minor modifications to the code (see below)

2021-04-01 09:53 UTC, pooja2299 commented on index.html
> -                            placeholder="Search for concepts, type at least two characters here."
@hmenager changes done :thumbsup:. Have a look. Also @bryan-brancotte , search icon was already there so I didn't add it :blush: .

2021-04-01 09:56 UTC, pooja2299 commented on index.html
> -                            placeholder="Search for concepts, type at least two characters here."
Also it is showing some conflict in my PR. Can you guide me to resolve it?

2021-04-01 12:12 UTC, hmenager commented on index.html
> -                            placeholder="Search for concepts, type at least two characters here."
ok, first let me resolve this comment, then we can discuss the conflict in PR main comments!

2021-04-01 12:13 UTC, hmenager approved these changes

2021-04-01 12:21 UTC, hmenager commented
@pooja2299 to resolve the conflict here, the easiest way would be to **click on the "resolve conflict" button** on this page. It should take you to a web editor where you can see the conflict as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/1140736/113292536-f0873380-92f4-11eb-8acf-daa29202d83d.png)
The conflict is shown in lines 122 to 126, with your version being in line 123 and the current main version being in line 125.
Here, all you have to do is **remove lines 122 and 124-126**, to keep the version of the code in line 123. 
Then, you can validate by clicking on the "Mark as resolved" button at the top right corner of this same page, and the conflict should be solved.

2021-04-01 14:00 UTC, pooja2299 commented
Conflict resolved!:grin: Thanks @hmenager for such detailed guidance.

2021-04-01 23:00 UTC, matuskalas commented
Should we merge this now @bryan-brancotte & @hmenager ?

2021-04-02 08:06 UTC, hmenager approved these changes

2021-04-02 08:25 UTC, hmenager commented
@bryan-brancotte will not be much available today, so since I discussed this PR yesterday with him, I won't request a formal review from him today :)

2021-04-02 08:25 UTC, merged