Modified PR Template added
edamontology/edam-browser pull request #94
Opened 2021-04-08 16:29 UTC by raashika03

@bryan-brancotte

2021-04-13 14:42 UTC, bryan-brancotte requested changes

2021-04-13 14:42 UTC, bryan-brancotte commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- [x] Note the issue (if any) closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
checkboxs should not be checked

2021-04-13 16:24 UTC, raashika03 commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- [x] Note the issue (if any) closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
Done @bryan-brancotte

2021-04-15 18:20 UTC, raashika03 commented
should i add this line also. 
`Put an x in the boxes that apply`

2021-04-26 13:07 UTC, bryan-brancotte commented
Was indeed needed ! I added content to the template, now merging

2021-04-26 13:08 UTC, bryan-brancotte approved these changes

2021-04-26 13:08 UTC, merged

2021-04-26 13:10 UTC, raashika03 commented
I was thinking to add few more points but was not sure if I should add. 
Now you added properly 🙏👏👏👏thank you @bryan-brancotte