Dark-mode implemented
edamontology/edam-browser pull request #96
Opened 2021-04-09 00:55 UTC by raashika03

closed #71 cause that had changes for other issues also, 
This's a clean PR with changes only related to this issue #60

2021-04-11 00:44 UTC, raashika03 commented
Hi @bryan-brancotte can this be merged if This's all OK. 
Further on I've thought to do something like this 
![IMG_20210411_060910](https://user-images.githubusercontent.com/45493793/114288335-7c832300-9a8c-11eb-96b1-c05720fd59b9.jpg)
Will put that theme button into some Menu with some other options as discussed in #62 #77, It'll be better from designing point of view. 
But since that's quite different issue from this, so want to handle this thing in some other pr. 
Then it'll be easier for me to work on.

2021-04-11 00:57 UTC, raashika03 commented
Or you can check this source (https://www.covid19india.org/) menu option, where that theme functionality is added. 

Will take inspiration for the basic design from above website and for positioning will take from gitter shown above.

2021-04-12 21:30 UTC, raashika03 commented
No sorry this can't be done as now only, I noticed that splashscreen/about menu discussed to be implemented in #77 will be positioned in the footer so going on with the theme button at the present position seems good. It has to be at the top part of the main page. So this's all ok. No work needed further.

2021-04-14 14:10 UTC, raashika03 commented
@bryan-brancotte any comments

2021-04-22 14:46 UTC, hmenager requested changes
Hi @raashika03 it looks like I forgot to finalize my review and that means you couldn't see my comments. I am very very sorry for that! I was wondering myself why you weren't answering :flushed:. Can you have a look at my comments and see what you can or cannot do?

2021-04-22 14:52 UTC, raashika03 commented on edit.html
> +        <script>const btn = document.querySelector(".btn-toggle");
Ok let me try to put it in utils.js.
At first I tried to put it in some js file (index.js) only but then it didn't work, couldn't figure out about utils.js though. So finally left it in the HTML.
But now I'll try again. Thank you @hmenager for the review.

2021-04-22 14:58 UTC, raashika03 commented on css/index.css
> +
Ok you mean I should create a separate file named as Dark-mode.css kind, then will import it in both index.html and edit.html. 
At present I put the css for all the elements of front page in index.css then for specific elements present only in propose change pages for which overriding is needed, I kept in bootstrap.xl.css. And imported index.css in edit.html for using all the basic same styling.

Or do you mean I should keep all in index.css?

2021-04-22 15:02 UTC, raashika03 commented on index.html
> +        <button class="btn-toggle" title="Change theme mode">
Yes, I was thinking the same. But was waiting for mentors to reply for the positioning of the button.
Yes, it disaligns that panel. let me see where it'll fit nicely.

2021-04-22 15:09 UTC, raashika03 commented on css/index.css
> +
@hmenager Please reply here asap. Needs a small clarity.

2021-04-22 15:25 UTC, raashika03 commented on index.html
> +        <button class="btn-toggle" title="Change theme mode">
But bottom-right do you mean in the line of previously seen option or exact at the bottom right in the line of communication logos. But positioning theme button at the bottom isn't a nice idea. It's not easy to notice if it's at the bottom of the page.

2021-04-22 15:35 UTC, raashika03 commented on index.html
> +        <button class="btn-toggle" title="Change theme mode">
Or I can place it at the position of "collapse not selected elements" where it's empty now after positioning that on the tree map. so bottom left sounds better than bottom right.

2021-04-22 17:53 UTC, raashika03 commented
Showing the theme button position for both desktop/ smartphone sizes. I placed it at the bottom left of tree-map cause there's no space on the bottom-right side.
![Screenshot from 2021-04-22 22-56-24](https://user-images.githubusercontent.com/45493793/115762709-62690f00-a3c1-11eb-9347-b4ee0fc54590.png)
![Screenshot from 2021-04-22 22-56-03](https://user-images.githubusercontent.com/45493793/115762723-6563ff80-a3c1-11eb-824a-155764d51a50.png)

2021-04-22 18:25 UTC, raashika03 commented
I removed this [error](https://github.com/edamontology/edam-browser/pull/96/commits/2f39ca8394eae8f15ad5023259001e1a0b634170) which got into this commit.
So, everything is ok now.

2021-04-22 21:25 UTC, hmenager requested changes
Hi @raashika03 thanks a lot for all these improvements (and I'm very sorry for not finalizing my previous review earlier). Do you think you can make it so that the function defined in both index.js and edit.js is only defined once in utils.js (or another standalone js file if you prefer)? Please let me know if help is needed.

2021-04-22 21:27 UTC, hmenager commented
> I removed this [error](https://github.com/edamontology/edam-browser/pull/96/commits/2f39ca8394eae8f15ad5023259001e1a0b634170) which got into this commit.
> So, everything is ok now.
> 
> I tried to remove that single line change in bootstrap.xl.css.
> But couldn't don't know why sweat

No worries about this, this is probably only a minor carriage return added automatically by your editor. :+1:

2021-04-23 03:22 UTC, raashika03 commented
Done @hmenager :sweat_smile: I should've done that before but I missed it anyhow while changing so many things.

2021-04-24 15:54 UTC, hmenager approved these changes
Looks good to me, thank you @raashika03 !

2021-04-24 15:54 UTC, merged