Tooltips for various tags in Term Details panel
edamontology/edam-browser pull request #99
Opened 2021-04-09 13:08 UTC by drashti171299

I have changed the code according to the suggestion of @bryan-brancotte . I have added tootips. let me know is there any change or not.

2021-04-13 12:28 UTC, drashti171299 commented
@bryan-brancotte  is there any mistake in code?

2021-04-13 14:18 UTC, bryan-brancotte requested changes
Hi @drashti171299

I like the approach, there is a typo to fix and a choice to do, I let you continue this PR and commit needed changes.

2021-04-13 14:18 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +        $("<tr><th data-toogle=\"tooltip\" title=\""+tootip+"\">"+name+"</th><td class=\""+id+"\">"+interactive_edam_uri(value, translate_uri_to_text)+"</td></tr>").appendTo(table);
there is a typo, it is not `data-toogle` but `data-toggle`

2021-04-13 14:18 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +        $("<tr><th data-toogle=\"tooltip\" title=\""+tootip+"\">"+name+"</th><td class=\""+id+"\">"+interactive_edam_uri(value, translate_uri_to_text)+"</td></tr>").appendTo(table);
You are using boostrap tooltip, but did not enabled them. I let you find how to do it. You can also decide to not use them, but in this case please justify it (in 1-2 sentences, I just want your opinion)

2021-04-13 14:18 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +            var id_b = append_row(community,"<a target=\"_blank\" href=\"https://bio.tools\">bio.tools</a>","<i>loading</i>","Bioinformatics Tools and Services Discovery Portal");
good idea to also rework them so every title are created in only one place, even for existing code

2021-04-13 16:11 UTC, drashti171299 commented on js/tree-edam-stand-alone.js
> +        $("<tr><th data-toogle=\"tooltip\" title=\""+tootip+"\">"+name+"</th><td class=\""+id+"\">"+interactive_edam_uri(value, translate_uri_to_text)+"</td></tr>").appendTo(table);
yes sure. I will try to look for this and enable bootstrap. Also, I will change this typo. It was my mistake.

2021-04-13 16:14 UTC, drashti171299 commented on js/tree-edam-stand-alone.js
> +            var id_b = append_row(community,"<a target=\"_blank\" href=\"https://bio.tools\">bio.tools</a>","<i>loading</i>","Bioinformatics Tools and Services Discovery Portal");
I didn't understand this. what change is required in this?

2021-04-14 05:58 UTC, drashti171299 commented
@bryan-brancotte I have updated the code. Have a look at that !

2021-04-22 13:07 UTC, drashti171299 commented
@bryan-brancotte  can you verify these changes and close this PR? Outreachy applications are due in few days.

2021-04-22 21:41 UTC, hmenager commented on js/tree-edam-stand-alone.js
> +            var id_b = append_row(community,"<a target=\"_blank\" href=\"https://bio.tools\">bio.tools</a>","<i>loading</i>","Bioinformatics Tools and Services Discovery Portal");
I don't think any change is needed here, it was just an appreciation of your coding strategy :smile:

2021-04-22 22:04 UTC, hmenager approved these changes
Looks good to me, thank you @drashti171299!

2021-04-22 22:05 UTC, hmenager commented on js/tree-edam-stand-alone.js
> +        $("<tr><th data-toogle=\"tooltip\" title=\""+tootip+"\">"+name+"</th><td class=\""+id+"\">"+interactive_edam_uri(value, translate_uri_to_text)+"</td></tr>").appendTo(table);
fixed AFAIK

2021-04-22 22:07 UTC, hmenager commented on js/tree-edam-stand-alone.js
> +        $("<tr><th data-toogle=\"tooltip\" title=\""+tootip+"\">"+name+"</th><td class=\""+id+"\">"+interactive_edam_uri(value, translate_uri_to_text)+"</td></tr>").appendTo(table);
fixed I guess

2021-04-23 03:24 UTC, drashti171299 commented on js/tree-edam-stand-alone.js
> +        $("<tr><th data-toogle=\"tooltip\" title=\""+tootip+"\">"+name+"</th><td class=\""+id+"\">"+interactive_edam_uri(value, translate_uri_to_text)+"</td></tr>").appendTo(table);
yes it is fixed now @hmenager.

2021-04-23 03:25 UTC, drashti171299 commented on js/tree-edam-stand-alone.js
> +            var id_b = append_row(community,"<a target=\"_blank\" href=\"https://bio.tools\">bio.tools</a>","<i>loading</i>","Bioinformatics Tools and Services Discovery Portal");
Thank you @hmenager. But if any change is needed, I am happy to do that

2021-04-26 10:37 UTC, bryan-brancotte requested changes
Hi @drashti171299 

I added some minor remarque on code submitted. I reviewed your code and the tooltip are not actually enabled, I let you find why. 

After enabled it I get that:
![tooltip-99](https://user-images.githubusercontent.com/11556772/116069358-92e3ce00-a68b-11eb-8ac9-297c2b72b757.gif)

So the roadmap is:
 * enable the tooltip
 * understand the UI glitch
 * fix the UI glitch

2021-04-26 10:37 UTC, bryan-brancotte commented on index.html
> +
not needed, please remove this line

2021-04-26 10:37 UTC, bryan-brancotte commented on css/index.css
> +    cursor: pointer;
Indeed the text pointer is not adapted, `pointer` is good, but i would rather use `default`

2021-04-28 08:44 UTC, drashti171299 commented on css/index.css
> +    cursor: pointer;
Okay I will remove this

2021-04-28 08:49 UTC, drashti171299 commented on index.html
> +
the last one should be removed only right?

2021-04-28 09:11 UTC, bryan-brancotte commented on index.html
> +
indeed only the newly added line, the idea is to not add blank line/change format when not necessary

2021-04-28 09:17 UTC, drashti171299 commented
@bryan-brancotte I am still not able to figure out why the bootstrap tooltips are not being enabled or what mistake I am doing in the code. but rest of your suggestions, I have done that thing. Review the code once again and tell me any other change you want in the code.

2021-04-28 10:37 UTC, bryan-brancotte reviewed
The issue was that you call `$('[data-toggle="tooltip"]').tooltip("enable");` only once when the app start, but at this moment the element that will later appear on the right does not exist yet, and thus not tooltip can be enabled. For example see [here](https://github.com/edamontology/edam-browser/pull/99/files#diff-c11ae8cf18cba2e900b4eee3972122950380827115f0cfb873ad70ba03280aa6R343), you can see that once the row is added we trigger the popover for this row.

2021-04-28 10:41 UTC, bryan-brancotte commented on index.html
> +
Hi, I only said to remove the newly added blank line, not the levenshtein !

2021-04-28 10:46 UTC, drashti171299 commented on index.html
> +
Ohk sorry for misunderstanding @bryan-brancotte . I am correcting it.

2021-04-28 10:49 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +        $("<tr><th><a href='#' data-toggle=\"tooltip\" data-placement='top' title=\""+tootip+"\">"+name+"</a></th><td class=\""+id+"\">"+interactive_edam_uri(value, translate_uri_to_text)+"</td></tr>
you fixed the flickering issue with moving the title to a sub elements :clap:

2021-04-28 10:52 UTC, drashti171299 commented on js/tree-edam-stand-alone.js
> +        $("<tr><th><a href='#' data-toggle=\"tooltip\" data-placement='top' title=\""+tootip+"\">"+name+"</a></th><td class=\""+id+"\">"+interactive_edam_uri(value, translate_uri_to_text)+"</td></tr>
Okay @bryan-brancotte.

2021-04-28 10:52 UTC, drashti171299 commented on js/tree-edam-stand-alone.js
> +        $("<tr><th><a href='#' data-toggle=\"tooltip\" data-placement='top' title=\""+tootip+"\">"+name+"</a></th><td class=\""+id+"\">"+interactive_edam_uri(value, translate_uri_to_text)+"</td></tr>
so the UI glitch is solved right?

2021-04-28 11:03 UTC, bryan-brancotte requested changes
Hi, I pushed where the enabling should be done in 6dc25f79dd06f9c5d29f34f3792f1b0a43b4f7cc, once the span used, we are good for merge

2021-04-28 11:04 UTC, bryan-brancotte commented on js/tree-edam-stand-alone.js
> +        $("<tr><th><a href='#' data-toggle=\"tooltip\" data-placement='top' title=\""+tootip+"\">"+name+"</a></th><td class=\""+id+"\">"+interactive_edam_uri(value, translate_uri_to_text)+"</td></tr>
yes UI glitch solved

2021-04-28 11:04 UTC, bryan-brancotte commented on index.html
> +
corrected

2021-04-28 11:04 UTC, bryan-brancotte commented on index.html
> +
corrected with https://github.com/edamontology/edam-browser/pull/99/commits/66a7b33a19a2800775ce400e6f3cb0424584573d

2021-04-28 11:05 UTC, bryan-brancotte commented on css/index.css
> +    cursor: pointer;
I was suggesting to set cursor to default, see https://github.com/edamontology/edam-browser/pull/99/commits/d18935203862221e3ee6cb0f061cbe5733f79440 for updated css

2021-04-28 11:13 UTC, drashti171299 commented on js/tree-edam-stand-alone.js
> +        $("<tr><th><a href='#' data-toggle=\"tooltip\" data-placement='top' title=\""+tootip+"\">"+name+"</a></th><td class=\""+id+"\">"+interactive_edam_uri(value, translate_uri_to_text)+"</td></tr>
okay you are right. as a user, I can also confused like why here is link

2021-04-28 11:15 UTC, drashti171299 commented on js/tree-edam-stand-alone.js
> +        $("<tr><th><a href='#' data-toggle=\"tooltip\" data-placement='top' title=\""+tootip+"\">"+name+"</a></th><td class=\""+id+"\">"+interactive_edam_uri(value, translate_uri_to_text)+"</td></tr>
I have changed the code. Have a look at that @bryan-brancotte

2021-04-28 11:18 UTC, merged

2021-04-28 11:18 UTC, drashti171299 commented
@bryan-brancotte  if you want any change, let me know. and thanks for guiding me in enabling tooltip.